layout 'pippo/000base.groovy',
applicationName: applicationName,
applicationVersion: applicationVersion,
runtimeMode: runtimeMode,
statusCode: statusCode,
statusMessage: statusMessage,
stacktrace: stacktrace,
requestMethod: requestMethod,
requestUri: requestUri